name: on-commit-deploy

on:
    push:
        branches: [ main ]
    
jobs:
    depl:
      runs-on: self-hosted   
      strategy:
        matrix:
              node-version: [18.x]             
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npm i -D @sveltejs/adapter-node@next
        - run: npm run build
        - run: pm2 restart App
        
